--
-- entropoy.mac
-- list_tooltip.lua
-- 
--
--



function tooltip (debug, tooltip)
  if tip.switch and tooltip ~= nil then
    if ImGui.IsItemHovered() then
      ImGui.BeginTooltip()
      ImGui.Text(tooltip)
      ImGui.EndTooltip()
    end   
  end  

end

tip = {
  switch = true,  -- true/false master control switch for all tooltips
  brd = "Bard",
  bst = "Beastlord",
  ber = "Berserker",
  clr = "Cleric",
  dru = "Druid",
  enc = "Enchanter",
  mag = "Magician",
  mon = "Monk",
  nec = "Necromancer",
  pal = "Paladin",
  rng = "Ranger",
  rog = "Rogue",
  shd = "Shadow Knight",
  shm = "Shaman",
  war = "Warrior",
  wiz = "Wizard",
  here = "emergency force combat in position",
  intervention_pull = "single intervention pull request",
  gather = "gather your toons to you", 
  noinvis = "remove all invis",
  stackinvis = "attempt to stack invis/ivu",
  incharge = "set yourself as control toon",
  all_tie_stick = "set all toons tie to moveutils stick",
  all_tie_nav = "set all toons tie to nav",
  all_auto = "set all toons to auto",
  all_manual = "set all toons to manual",
  auto = "self auto on/off",
  all_tie = "set all toons tie on/off",
  macro_auto = "set manual mode",
  macro_manual = "set auto mode", 
  ui_drive = "ui: drive",
  ui_radar = "ui: radar", 
  ui_radar_start = "ui: radar start", 
  ui_radar_stop = "ui: radar stop", 
  ui_hud_start = "ui: hud start", 
  ui_hud_stop = "ui: hud stop",   
  ui_movement = "ui: movement",
  start_healing = "start healing at ",
  never_heal = "never heal ",
  list_clear = "clear list",
  swAgro = "try to get agro on current target",
  stPctAgroHold = "[##]% minimum % off hate to try to hold on current target",
  stPctTaunt = "[##]% hate % to use taunt", 
  swBuffAura = "enable aura buffs",
  swBuffSelf = "enable self buffs",
  swBuffCrew = "enable buffs for all dannet crew",
  swBuffTemp = "enable temp buffing",
  swBuffUnity = "enable using class unity buff",
  swPetBuff = "enable buffing your pet",
  swBuffRaid = "enable buffing raid members",
  swBuffGroup = "enable buffing group memebers (not the same as crew)",
  swBuffNow = "enable now buffs",
  swBuffAmmo = "enable summoning ammo",
  swBuffBeg = "enable begging other buff classes",
  swBuffNoLobby = "disable buffing in lobby zone",
  stAAUnity = "class unity buff",
  swBuffShrink = "enable self shrinking",
  stShrinkHeight = "[##] height to shrink to",
  stShrinkItem = "what to shrink with",
  swBurnForce = "force burns all the time. ABB Baby!",
  swBurnAuto = "enable auto burns on established named mobs",
  swBurnRaid = "enable burns in raids",
  stPctBurnEngage = "[##]% of target health to start burns",
  stBurnCount = "[##] mobs in /env rad to engage burns",
  swCombatDoT = "enable dots during class routines",
  swCombatHeal = "enable healing during class routines",
  swCombatMelee = "enable melee during class routines",
  swCombatRange = "enable ranged combat during class routines",
  swCombatNuke = "enable nuking during class routines",
  swCombatControl = "enable crowd control during class routines",
  stPctEngage = "% of targets health to engage",
  stZRadius = "Z axis range to engage target",
  swManualAssist = "force manual assisting over auto",
  swStoponDS = "try to stop attacking when target has a DS",
  stAssistMode = "sets type of automated assist to acquire targets",
  lsAss = "list of other people for manual assisting",
  lsNoCastWith = "list of debuffs on you to halt casting",
  lsNoMeleeWith = "list of debuffs on you to halt melee",
  swGlyphGroup = "use glyps in groups",
  swGlyphRaid = "use glyphs in raids",
  stGlyph = "glyph to be used",
  button_alt = "alternate abilities",
  button_pulse = "bard songs",
  button_spell = "cast spells that take mana",
  button_disc = "melee disciplines",
  button_item = "physical items to click",
  button_ability = "other abilities like kick or punch",
  swIntensityGroup = "use intensity while in group on burns",
  swIntensityRaid = "use intensity while in raids on burns",
  stAAIntensity = "name of intensity aa",
  stFade = "class fade aa name",
  stPctFade = "[##]% of health to attempt to fade",
  ccl_cure = "check and cycle curing [/cure]",
  ccl_melee = "cycle melee skills [/melee]",
  ccl_heal = "check and cycle healing [/heal]",
  ccl_burn = "check and apply burn ointments [/burn]",
  ccl_misc = "",
  ccl_dot = "moar dots [/dot]",
  ccl_nuke = "nuke a thing [/nuke]",
  ccl_debuff = "talk smack [/debuff]",
  ccl_item = "cycle items to click [/clickitem]",
  ccl_pet = "send cat to knock over drinks",
  ccl_swarm = "throw bees at younger sister",
  ccl_manarecover = "try to get some mana back",
  ccl_staminarecover = "try to get stamina back",
  ccl_checkminion = "check pet for bruises and splinters",
  ccl_xtarget = "correct xtarget lists",
  ccl_agro = "cycle agro skills [/agro]",
  ccl_cc = "cycle and verify crowd control",
  ccl_gather = "gather mana skills",
  ccl_mode = "do mode thing'ies [/mode]",
  ccl_pulseic = "sing songs while in combat",
  ccl_miscdps = "cycle misc dps skills [/miscdps]",
  tiCheck_Para = "[##s] timer to check for paragon needs",
  stCountAE = "[##] # of mobs in close area to activate AS. 0=off",
  stSynergy = "class synergy",
  swCureCrew = "attempt to cure your dannet boxes",
  swCureGroup = "attempt to cure your group",
  swCureSelf = "you were warned to wear protection..",
  lsNoCure = "list of things to never cure",
  tiCheck_Watch = "[##s] time for refresh of watched spawns",
  swWatchBeep = "make couputer do an old school beep whem a mob on the list spawns",
  swWatch = "enable watching for spawns in the zone",
  lsWatch = "list of mobs to watch in the zone",
  tiCheck_VoT = "[##]s/m timer check for vot use",
  stDotRefresh = "[##]s time left on dot to refresh",
  stPctStopDoT = "[##]% percent of mobs health to stop dotting; 0=disable",
  alternateline = "alternate use order",
  stCountMezResist = "max tries before you give up",
  stCountDef = "[##] mobs in close range to start defensive", 
  stPctDef = "[##]% health to start defensives", 
  stRNDEngage = "[##] randomize engage %",
  stRNDEngagePet = "[##] randomize engage pet %",
  stRNDEngageSwarm = "[##] randomize engage swarm %",
  stRNDEngageBurn = "[##] randomize engage burn %",
  stRNDRezTake = "[##] randomize delay to accept rez (10th/sec)",
  stRNDRepeat = "[##] randomize delay time to echo /repeat (10th/sec)", 
  swAutoList = "autopopulate zone listsnames for some mob types",
  swBuffCooldownWait = "force a wait between buffs for cooldown to do complete cycle",
  swUseConColor = "use ConColors for targets",
  swTLP = "TLP player",
  swBuildSetRemember = "remember and refresh a set on macro boot",
  swRelayTell = "relay tells to the tie toon",
  swRelayTellBeep = "beep on a tell relay",
  swMaintenance = "place entropy in a limited maintenance mode for operations",
  swAutoInvManual = "obey autoinventory fast list even in manual mode",
  swEventsInc = "obey autoinventory fast list even in manual mode",
  swHookSub = "allow hook functions in subs",
  stCastLoop = "number of castloop attempts, event based",
  stCountFizzleRetry = "number of cast retrys on a fizzle",
  stMainLoopDelay = "this is the main delay for the master macro loop. USE CAUTION when changing!",
  swAAFireworks = "waste aa on fireworks",
  swSafeListGuild = "auto include your guilnd in your safe list",
  tiCheck_EXP_Adjust = "timer to check for exp adjust",
  lsAutoInventory = "list of items to auto inventory",
  swAutoInv = "enable autoinventory of listed items",
  tiCheck_FoodDrink = "time to check for snacks",
  stFood = "food item for that 4 am snack",
  stDrink = "no i dont have a problem, you do",
  stLvlPct = "[##]% of exp in a level you want to maintain", 
  stLvlMax = "[##] level you want to maintain",
  swCheckTribute = "check and corect tribute for raids",
  swTakeGroupInvite = "auto take group invite from safe list",
  swTakeRaidInvite = "auto take raid invite from safe list",
  stBuffGem = "gem slot to use for buffing",
  swHoldBuffGem = "remember and return the spell used in that slot before buffing",
  stMobLvlMin = "[##] minimum level of a mob you are wiling to engage",
  stMobLvlMax = "[##] maximum level of a mob you are wiling to engage",
  stEnvRadius = "[##] radius you are willing to operate in",
  stEnvSafeRadius = "[##] radius you consider safe even with mobs in it",
  swCorrectEXPAA = "use exp/aa adjust functions",
  stBuildSetCurrent = "name of current build set",
  swDropBuffs = "enable dropping buffs",
  lsDropBuffs = "list of buffs to drop",
  tiCheck_Drop_Buffs = "timer to check to drop buffs",
  lsNoCastBuff = "no casting with these buffs on",
  swAlwaysDropInvisCauseThePeopleIGroupWithAreAssHats = "drop invis always!",
  swIgnoreInvis = "ignore invis when casting or melee, does not drop it",
  swBegMAG = "enable groveling to mages for stuff",
  swSoS = "enable use of automated sos",
  swOverLOS = "override line of sight validations",
  swOverPctEngage = "[##]% override engage for all types, instant engage of a target",
  swOverLoot = "attempt to loot regardless of master looter in group or raid",
  swOverSafeNames = "ignore safename checks, trust everyone. dm me your account info please",
  swOverTrainSpell = "ignore spell training caps. to the moon alice",
  swOverEnvAuto = "ignore non-persistent auto and start with /env auto on",
  swOverDSCheck = "ignore damage shield checks while melee",
  swOverNavCheck = "bypass Nav PathExists checks",
  swOverGroupAss = "override group assist rules",
  swOverSplashHurt = "override hurt requirements for splashing (try to keep it in cooldown no matter what)",
  swTargetClear = "override clearing targets",
  swOverMaxMelee = "override max melee adjustments in combat. right here is good!",
  swTash = "enable tashing a target",
  swMez = "enable mezing a target",
  swSnare = "enable snaring a target",
  swSlow = "enable slowing a target",
  swMalo = "enable maloing a target",
  swEradicate = "enable eradicate aa on a target",
  swCripple = "enable crippling a target",
  lsOrderClassBase = "class base loop start",
  lsOrderClassPre = "class pre combat",
  lsOrderClass = "class active combat order",
  lsOrderClassPost = "class post combat",
  lsOrderCastType = "execute type search order",
  stInvisSingle = "self invisibility",
  stInvisGroup = "group invisibility",
  stInvisSingleIVU = "self invis vs undead",
  stInvisGroupIVU = "group invis vs undead",
  stInvisDelay = "[##] 1/10s delay in casting from command issue. helps to stack invis with some classes",
  stSpire = "name of class spire AA",
  swSpireRaid = "use spire in raids on burns",
  swSpireGroup = "use spire in group on burns",
  swHealSelf = "enable self healing",
  swHealDanNet = "enable use of DanNet for healing",
  swHealGroup = "enable group healing",
  swHealPet = "enable pet healing",
  swHealWeighted = "enable weighted HP check healing",
  swBreakHealPCT = "enable a stop heal when target is > its heal point",
  stHealAdjust = "[##] % to overide max health to",
  stRampageTank = "rampage tank to not heal; completely ignore",
  lsOrderHeal = "heal cycle order",
  lsHealXTClass = "classes to populate xtarget for healing use",
  lsProtectOutsideGroup = "names outside of your group to add to xtarget for healing",
  lsPosition = "random list for mob facing",
  swonAuto = "set home camp on auto",
  swinCombat = "keep home camp while in combat",
  swMoveGatherClear = "on = clear home marker when a gather is issued",
  swMoveDeathClear = "on = clear home marker and movements on death",
  swFaceFast = "use fast facing movements",
  stHomeVariance = "[##] acceptable buffer range for being home",
  stFaceArc = "[##]% (1-45) acceptable range of facing and still be on target",
  swPet = "master pet switch, disable to prevent all pet use",
  swPetShrink = "yes, you should shrink your pet.. ffs",
  swSwarm = "use swarm pets",
  swNoSwarmonDS = "dont use swarm pets on targets with a DS",
  swonForce = "focse pet attack on /control force",
  swUsePetGear = "use pet gear if you have it on you",
  stPctPetEngage = "[##]% of targets health to send in pet",
  stPetIllusion = "illusion item to use on your pet",
  stPetShrink = "item/aa/spell to shring your pet with; 2x",
  stPctSwarmEngage = "[##]% of targets health to send in swarm pets",
  stPetWeapon = "mage pet weapon type to fead your pet",
  stBegAlias = "alias you use to respond",
  swNukeLoop = "lock the nuke loop; do all nukes before releasing the class to do other things",
  swNukeWhackAMole = "try to sit between nukes to med",
  stNukeDelay = "[##]s additional seconds to delay between each nuke",
  stPctStopNuke = "[##]% pct of targets health to stop nuking it",
  swRestFull = "rest to full health if possible",
  swRestModRod = "use mod rods while resting",
  swRestBuff = "do buffing while resting",
  swRestCombat = "continue resting while in combat",
  swRestCheckHealth = "check health as well when resting",
  swRestInRaid = "enable resting while in raids",
  stPctRest = "[##]% rest when health/manna below this number",
  stRestRadius = "[##] no mob in this radius for resting",
  stRestSpawnSearch = "[spawnsearch] search criteria for hostile mobs close to you",
  lsRezIC = "names of in combat rezes",
  lsRezOOC = "names of out of combat rezes",
  lsNoRezToon = "names of people you never want to rez",
  stRezSummonRange = "[##] /corpse summon range when rezing",
  stMaxRezRange = "[##] how far away to look for corpses to rez",
  swRezIC = "rez while in combat",
  swRezOOC = "rez while out of combat",
  swRezDanNet = "rez your DanNet peoples",
  swRezEveryone = "rez anyone.. we just don't care",
  swRezToken = "use rez tokens",
  swRezTake = "auto take take rezes",
  swRezTakeCall = "auto take call to corpse",
  swHardStopRez = "stop pulling when someone has rez effects",
  stPctHardStop = "[##]% of crew sta/manna to stop pulling at to give them rest time?",
  stHardStopDuration = "[##s/m] duration to stop pulling for crew to recover",
  stPullRadius = "radius to pull mobs from",
  stPullZRadius = "the z distance of your pulling environment",
  stPullNavStopDistance = "how close you will nav pull to a mob before trying too tag it",
  stPullNavVariance = "[##]% variance added to pull radius to exceed nav pull lengths to get to a mob",
  stRangeBandolier = "name of bandolier for ranged pulling?",
  stPullOutrunRange = "[##] slow down range when pulling a mob back to camp so you dont outrun them",
  stCountChainPull = "[##] of mobs left in area to go pull more",
  stPullPetWatch = "radius to pull dumb ass NPC pets",
  swPull = "enable pulling",
  swPullNavLoS = "is Line of Sight (LOS) required for nav pulling",
  swNavPathLogic = "use nav path lenght logic for finding targets to pull",
  swPullHealCheck = "self healing check while pulling",
  swPullSetHome = "auto set home marker when pulling is enabled",
  swHUDAuto = "HUD on mac start",
  swHUDDriveAuto = "crew drive on mac stary",
  swHUDEventButtonsAuto = "event button bar on mac start",
  stRadarAuto = "radar on mac start",
  
  swHUDBTNallauto = "set all toons to auto",
  swHUDBTNallmanual = "set all toons to manual",
  swHUDBTNauto = "set your toon to auto",
  swHUDBTNtie = "enable tie",
  swHUDBTNtienav = "set tie mode to nav",
  swHUDBTNtiestick = "set tie mode to stick",
  swHUDBTNincharge = "set yourself as the in charge toon",
  swHUDBTNinvis = "",
  swHUDBTNnoinvis = "",
  swHUDBTNintpull = "request single intervention pull from nearest cleric",
  swHUDBTNgather = "gather your toons to you",
  swHUDBTNhere = "sent all toons to combat now!",
  swHUDBTNradar = "",
  swHUDBTNdrive = "",
  swHUDBTNevent = "",
  swHUDBTNnotes = "",
  swHUDBTNmovement = "",
  swTitleEnt = "",
  swTitleBuild = "",
  swTitleName = "",
  swTitleAM = "",
  swTitleIV = "",
  swTitleIVU = "",
  swTitleHealAdj = "",
  swTabBuff = "",
  swTabHeal = "",
  swTabCombat = "",
  swTabPull = "",
  swTabRaids = "",
  swTabRez = "",
  swTabTie = "",
  swTabRest = "",
  swTabTarget = "",
  swHUDbuttons = "",
  swHUDDisplayName = "",
  stHUDBlank = "",
  tiAgro = "[##s] timer to slow down use of agro skills",
  tiWithstand = "[##s] (1-3 sec is good) timer to slow down knights spamming rune disc routine",
  swHealXTarget = "consider xtarget when healing",
  stPullMode = "method of mob pulling",
  stPullWith = "what to pull with",
  stPctMinRez = "minimum % rez to accept",
  stMaxRezRange = "max radius to look for corpses to rez",

  stTieMode = "mode used to follow the control toon",
  swTieCombat = "enable tie while in active combat. will adjust as often as possible",
  swTieBreak = "attempt to stop anything to force a tie movement",
  stTieToon = "name of toon you want to tie too when commanded",
  stTieVariance = "acceptabe distances to be away from the tie toon before moving to it",
  stPctRest = "",
  stRestRadius = "",
  swRestBuff = "",
  swRestFull = "",
  swRestCombat = "",
  swRestCheckHealth = "",
  swRestInRaid = "",
  swSplashMeOnly = "use youself as target for splashing",
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  





  -- dannet settings
    swLocalEcho = "dannet local echo",
    swCommandEcho = "dannet local command echo",
    swFrontDelim = "dannet lead front delimiters",
    swFullNames = "dannet use fullnames",
    swEvasiveRefresh = "refreshes observers if a client goes evasive",
    stNetworkEvasive = "dannet timeout client loss. set higher for laggy systems",
    stNetworkExpired = "dannet timeout to delete a peer",
    stDanNetQueryDelay = "delays for dannet query returns",
    stNetworkTimeout = "dannet timeout for network lag. ignore this if at all possible",
    stEntropyGroup_all = "dannet group communication channel",
  -- end dannet settings
  -- maHard settings
    stMaxMeleeAdj = "[##] % variance for max meele range adjustment",
    stRadGrab = "[##] pick up allowable 3d radius for EQ",
    stMaxRadPet = "[##] max usable range for pets",
    stMinBowDist = "[##] minimum distance to be able to bow or throw",
    stMaxBowDist = "[##] maximum distance to bow or throw",
    stMinMovetoBow = "[##] minimum distance to move to get bow/throw range",
    stRezSuccess = "[##s] timer reset to rez the same person on a success",
    stRezFail = "[##s] timer reset to rez the same person on a fail",
    stRezFailToken = "[##m] timer reset to rez the same person on a fail with a token rez",
    stRezSummonRange = "[##] /corpse summon range when rezing",
    stRezIgnoreFucktards = "[##m] mark no rez",
    stMaxCureRad = "[##] max radius to check for curing",
    stPullMobTagTry = "[##] max trys to tag a mob while pulling",
    stBardSwapRemain  = "[##] ms left on cast time to swap instrument in",
    stSpellBookSize = "[##] maximum # of spell book slots",
    stFoodMaintain = "[##] level of, i'm full, to maintain for food",
    stDrinkMaintain = "[##] level of, i'm not thirsty, to maintain for drink",
    stModeDragTargetCheck = "[##] speed that you grab another corpse to drag. lower = faster",
    stMaxSPARemoveCount = "[##] highest spa a spell/buff has to look at for removal",
    stDelayLua = "[##s] time to delay initial lua scripts to allow all variables to populate",
  -- end maHard

   
}
